/* Generated By:JJTree: Do not edit this line. ASTadd_expr.cs */

using System;

namespace parser {
    
public enum AddOps {
    Plus, Minus
}

public class ASTadd_expr : SimpleNode {
        
  #region IFields
    
  private AddOps m_operation = AddOps.Plus;
    
  #endregion IFields        
        
  public ASTadd_expr(int id) : base(id) {
  }

  public ASTadd_expr(IDLParser p, int id) : base(p, id) {
  }


  /** Accept the visitor. **/
  public override Object jjtAccept(IDLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public void SetAddOperation(AddOps operation) {
    m_operation = operation;
  }
    
  public AddOps GetAddOperation() {
    return m_operation;
  }  
  
}


}

